version: '3.9'
services:
  ineserver:
    build:
      context: ./IneServer
      dockerfile: Dockerfile
    image: omarahorrar/ineevents-ineserver:latest
    container_name: ineevents_server
    ports:
      - "5000:5000"
    env_file:
      - ./IneServer/.env
    networks:
      - ine_network

  ineclient:
    build:
      context: ./IneClient
      dockerfile: Dockerfile
    image: omarahorrar/ineevents-ineclient:latest
    container_name: ineevents_client
    ports:
      - "5173:80"
    stdin_open: true
    tty: true
    depends_on:
      - ineserver
    networks:
      - ine_network

networks:
  ine_network:
    driver: bridge